random_text = [
    "Got it, boss. I'm on the case !",
    "No worries, I’ve got this covered.",
    "Hang tight, I’m handling it now.",
    "On it like a pro, just give me a second !",
    "Consider it done, chief !",
    "Give me a moment, handling it like a boss.",
    "Working on it, you’ll have it in no time !",
    "Already on it, sit back and relax.",
    "Give me a beat, making it happen.",
    "This is in the bag, give me a second !"
]

repeat_cmd = [
    "Oops, missed that. Mind repeating?",
    "Sorry, I didn’t catch that. Can you say it again?",
    "My bad, could you run that by me once more?",
    "Didn’t quite get that, mind repeating?",
    "Sorry, can you hit me with that again?",
    "Could you repeat that real quick? I missed it.",
    "Come again? I didn’t catch that.",
    "Sorry about that, can you say it again?",
    "Wait, what? Can you repeat that for me?",
    "I missed that part, mind saying it again?"
]

vtron_health = [
    "I'm all good, running smooth as ever!",
    "Feeling awesome, thanks for asking!",
    "I'm in top shape, ready to go!",
    "All systems go, I'm doing just fine!",
    "I’m great, full steam ahead!",
    "I’m feeling fantastic, let’s roll!",
    "All good on my end, no worries!",
    "I'm doing great, ready for action!",
    "Feeling sharp, everything’s under control!",
    "Perfectly fine, firing on all cylinders!"
]

vtron_identity = [
    "who are you", "hu r u",
    "what is your name",
    "can you introduce yourself",
    "tell me about yourself",
    "what do you do",
    "who created you",
    "what are you",
    "what's your identity",
    "who made you",
    "who is your developer",
    "who built you",
    "describe yourself",
    "what is your purpose",
    "who programmed you",
    "what is your role",
    "what's your job",
    "are you an assistant",
    "who designed you",
    "who's behind your creation",
    "what can I call you",
    "are you human",
    "what are you capable of",
    "what should I know about you",
    "what's your function",
    "are you a bot",
    "how were you made",
    "why were you created",
    "who gave you life",
    "who is responsible for you",
    "who's your creator",
    "what is your purpose in life",
    "why do you exist",
    "are you an AI",
    "what's your origin",
    "where do you come from",
    "what's your backstory",
    "how do you work",
    "how were you programmed",
    "what's your full name",
    "are you intelligent",
    "who are you made by",
    "what technology are you built on",
    "are you a digital assistant",
    "why were you made",
    "what's your mission",
    "who's your father",
    "who's your parent",
    "what platform are you built on",
    "who developed you",
    "what's your background",
    "who do you belong to",
    "what kind of assistant are you"
]

vtron_thank_you_responses = [
    "You're welcome!",
    "No problem at all!",
    "Glad I could help!",
    "Happy to assist!",
    "Anytime, happy to help!",
    "No worries, you're welcome!",
    "It’s my pleasure!",
    "Always here for you!",
    "Glad I could assist!",
    "Don’t mention it!",
    "You're very welcome!",
    "Of course, happy to help!",
    "I'm here whenever you need me!",
    "No trouble at all!",
    "Feel free to ask anytime!",
    "You're most welcome!",
    "It was nothing!",
    "I’ve got your back!",
    "My pleasure entirely!",
    "Always at your service!"
]
